services:
  db:
    image: postgres:18
    restart: unless-stopped
    container_name: db_crm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql

  api:
    build:
      context: ./api
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: api_crm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db

  web:
    build: ./web
    container_name: web_crm
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
      - ./api/generated:/app/src/generated:ro

volumes:
  pgdata:
